"""Side effects live here and nowhere else (docs/02-LLD.md §8).

The LLM cannot issue a notice. Only this module writes artefacts, and only
from a validated Decision. Every artefact carries the simulated-case banner
and names providers by pseudonym alone (EC-1, AC-8).
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from crew.schemas import AGENT_TITLES, Action, Adequacy, Claim, Decision, Package, TriggerHit
from rules.triggers import field_checklist

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out"

BANNER = ("> **SIMULATED CASE.** Generated by *The Access Gate* on simulated input. The claim, the "
          "hospital's conduct and every allegation are fictional. District network figures are real published "
          "data; no real hospital is alleged to have done anything.")

LOG_FIELDS = ["case_id", "claim_id", "hospital_ref", "trigger_id", "triggers_fired", "severity", "action",
              "claim_withheld", "human_required", "gate", "confidence", "degraded", "channels_used",
              "field_channels_ordered", "district", "specialty", "n_providers", "km_to_alternative",
              "population", "aspirational", "capability_ok", "specialties_at_stake", "reason_codes", "conflicts",
              "artefact_path", "decided_ts", "model", "acted_by", "tools_called", "agents", "disputed"]

TITLES = {
    Action.SHOW_CAUSE: "Show-cause notice",
    Action.FIELD_AUDIT: "Field audit order",
    Action.SUSPEND: "Suspension order and referral to the State Empanelment Committee",
    Action.ESCALATE_SEC: "Escalation to the State Empanelment Committee",
    Action.DELIST_SPECIALTY: "Specialty de-listing referral and uncovered-district flag",
    Action.NO_ACTION: "Referral for human review",
}


def _inline(text: str) -> str:
    """Agent and field-team text on one line: a line break or a leading '#' in it would end the list item or open a
    heading of its own inside the artefact."""
    return " ".join(str(text).split())


def _mode(d: Decision) -> str:
    if not d.degraded:
        by = "executed by the Enforcement Officer" if d.acted_by == "enforcement_officer" else \
            "executed by the orchestrator: the officer did not act"
        return f"crew on {d.model}, {by}"
    return f"deterministic (degraded: {d.model} unavailable)" if d.model else "deterministic"


def _cell(text: str) -> str:
    return _inline(text).replace("|", "\\|") or "-"


def _title(agent: str) -> str:
    return AGENT_TITLES.get(agent, agent)


def _trail(d: Decision) -> list[str]:
    lines = ["## Investigation trail", "",
             "Every tool the agents called on this case, in order. A refused call is the tool declining: the officer's "
             "action tools execute only the enforcement policy's decision.", "",
             "| # | Agent | Tool | Arguments | Result |", "|---|---|---|---|---|"]
    for i, t in enumerate(d.trail, start=1):
        args = "; ".join(f"{k}={v}" for k, v in t.arguments.items())
        result = ("**refused** - " if t.refused else "") + t.outcome
        lines.append(f"| {i} | {_title(t.agent)} | `{t.tool}` | {_cell(args)} | {_cell(result)} |")
    return lines + [""]


def _review(d: Decision) -> list[str]:
    """The Audit Reviewer's check of the findings, before the policy decided on them."""
    disputed = (f"Disputed, and so set aside: {', '.join(d.disputed)}. A disputed finding weighs nothing: the reviewer "
                "can send a case to more evidence or to a human, never convict or clear it."
                if d.disputed else "No finding disputed.")
    refused = ([f"Disputed, and the dispute refused: {', '.join(d.disputes_refused)}. The reading rests on a "
                "comparison the claim store makes itself, and a dispute may set aside a reading, never a measurement."]
               if d.disputes_refused else [])
    return ["## Audit review", "", disputed] + refused + ([_inline(d.review)] if d.review else []) + [""]


def _router(d: Decision) -> list[str]:
    """What the Case Router added to the work the rules had already opened, and why (B-48)."""
    if not d.opened_by_router:
        return []
    return ["## Work the Case Router opened", "",
            "The rules open a case's mandatory investigations from its trigger and its file; the router may add to "
            "them and may never take from them. On this case it added:", ""] + \
        [f"- {_inline(r)}" for r in (d.router_reasons or d.opened_by_router)] + [""]


def _defence(d: Decision) -> list[str]:
    """The Provider Advocate's answer: the hospital's side, before it was acted against."""
    if d.defence is None:
        return []
    verdict = ("The evidence on file excludes it." if d.defence_excluded else
               "The evidence on file does not exclude it, so no action was taken that no human has reviewed.")
    return ["## The hospital's side (Provider Advocate)", "", _inline(d.defence), "", verdict, ""]


def _brief(d: Decision) -> list[str]:
    """The Committee Liaison's brief, filed with an escalation or a de-listing referral."""
    b = d.committee_brief
    lines = ["## Brief for the State Empanelment Committee", "",
             "*Prepared by the Committee Liaison. It recommends; the Committee decides.*", "", _inline(b.summary), "",
             "| Option | Consequence |", "|---|---|"]
    lines += [f"| {_cell(o.option)} | {_cell(o.consequence)} |" for o in b.options]
    return lines + ["", f"**Recommendation.** {_inline(b.recommendation)}", "",
                    f"**Question for the Committee.** {_inline(b.question)}", ""]


def alternative(a: Adequacy) -> str:
    """Where the next provider of the specialty is. Distances exist only for sole-provider cells; elsewhere the
    alternative is in the district itself, and 'no alternative listed' said the opposite of the truth."""
    others = a.n_providers - (1 if a.hospital_listed else 0)
    if others > 0:
        return f"in the district ({others} other provider{'s' if others != 1 else ''})"
    if a.n_providers == 0:
        return "none in the district (distances are computed for sole-provider districts only)"
    if a.km_to_alternative is None:
        return "none listed"
    return f"{a.nearest_alternative}, {a.km_to_alternative:.0f} km away"


def stake_phrase(a: Adequacy) -> str:
    """Why losing this hospital would cost the district a specialty, in words ('the only real provider of ...')."""
    if a.n_providers <= 1:
        where = ("no alternative listed" if a.km_to_alternative is None
                 else f"nearest alternative {a.km_to_alternative:.0f} km away in {a.nearest_alternative}")
        return f"the only real provider of {a.specialty_name} ({where})"
    return f"one of only {a.n_providers} providers of {a.specialty_name}"


def _access_block(d: Decision) -> str:
    a = d.adequacy
    if a is None:
        lines = ["Network adequacy could not be computed for the billed specialty."]
    else:
        lines = [
            "| Billed specialty | |", "|---|---|",
            f"| District | {a.district}, {a.state} |",
            f"| Specialty | {a.specialty_name} |",
            f"| Hospital empanelled for it | {'Yes' if a.hospital_listed else 'No'} |",
            f"| Empanelled providers in district | **{a.n_providers}** |",
            f"| Nearest other provider | {alternative(a)} |",
            f"| District population | {a.population:,} |",
            f"| NITI aspirational district | {'Yes' if a.aspirational else 'No'} |",
            f"| Capability flag | {'plausible' if a.capability_ok else 'IMPLAUSIBLE'} - {a.capability_reason} |",
        ]
    referral = d.action is Action.DELIST_SPECIALTY and d.access_at_stake
    if (d.action in (Action.SUSPEND, Action.ESCALATE_SEC) and d.gate in ("clear", "protect")) or referral:
        # A suspension removes the hospital from every specialty it is empanelled for, so all of them are shown --
        # on a de-listing referral too, because the Committee receiving it may choose to suspend.
        lines += ["", "**What a suspension would remove.** A suspension takes the hospital out of the scheme for every "
                      "specialty it is empanelled for."
                  + (" This referral de-lists one specialty; the table is for the Committee, should it consider "
                     "suspension." if referral else "")]
        if d.access_at_stake:
            lines += ["", "| Specialty at stake | Providers in district | Nearest other provider | "
                          "Why it is protected |", "|---|---|---|---|"]
            for x in d.access_at_stake:
                why = ("sole real provider" + (", NITI aspirational district" if x.aspirational else "")
                       if x.n_providers <= 1 else "one of two providers in a NITI aspirational district")
                lines.append(f"| {x.specialty_name} | **{x.n_providers}** | {alternative(x)} | {why} |")
        else:
            lines += ["", "No specialty it is empanelled for would lose its only real provider beyond reach."]
    return "\n".join(lines)


def render(d: Decision, claim: Claim, hit: TriggerHit | None, package: Package | None,
           draft: str | None = None) -> str:
    lines = [f"# {TITLES.get(d.action, d.action.value)}", "", BANNER, "",
             f"**Case** {d.case_id} · **Claim** {d.claim_id} · **Hospital** {d.hospital_ref} · "
             f"**Decided** {d.decided_ts:%Y-%m-%d %H:%M} · **Mode** {_mode(d)}",
             ""]
    if d.agents:
        lines += [f"**Agents** {' → '.join(_title(a) for a in d.agents)}", ""]
    if hit:
        lines += ["## Trigger", f"**{hit.trigger_id} — {hit.name}** (severity {hit.severity.value}). "
                                f"{_inline(hit.evidence)}.", f"*Source: {hit.source}*", ""]
    if package:
        # Published package names carry line breaks ("Bronchial artery Embolisation \n(for Haemoptysis)").
        published = (f"published rate Rs {package.amount_rs:,}" if package.amount_rs > 0
                     else "no fixed rate in the package master")
        lines += [f"**Package** {package.package_code} — {_inline(package.package_name)} ({published}; "
                  f"claimed Rs {claim.amount_claimed:,})", ""]
    lines += ["## Findings", ""]
    for f in d.findings:
        stance = {True: "supports", False: "opposes", None: "inconclusive"}[f.supports_fraud]
        where = f" / {f.channel.value}" if f.channel and f.channel.value != f.agent else ""
        lines.append(f"- **{f.agent}{where}** — {stance} ({f.confidence:.2f}): {_inline(f.conclusion)} "
                     f"*[{_inline(f.citation)}]*")
    if d.conflicts:
        lines += ["", "**Conflicts:** " + "; ".join(d.conflicts)]
    lines += ["", f"**Aggregate confidence:** {d.confidence:.2f} · **Reason codes:** `{', '.join(d.reason_codes)}`", ""]
    if d.opened_by_router:
        lines += _router(d)
    if d.defence is not None:
        lines += _defence(d)
    if d.review is not None or d.disputed:
        lines += _review(d)
    if d.trail:
        lines += _trail(d)

    if d.action in (Action.SUSPEND, Action.ESCALATE_SEC, Action.DELIST_SPECIALTY):
        lines += ["## Access impact", "", _access_block(d), ""]
    if d.action is Action.FIELD_AUDIT:
        lines += ["## Channels ordered", ""] + [f"- {c.value}" for c in d.field_channels_ordered]
        if d.field_questions:
            lines += ["", "## What the field team must establish in this case", ""] + \
                     [f"- {_inline(q)}" for q in d.field_questions]
        field_checks = field_checklist(hit.trigger_id) if hit else []
        if field_checks:
            lines += ["", "## What the field team checks (guidebook)", ""] + [f"- {c}" for c in field_checks[:8]]
        lines.append("")
    if d.action is Action.SHOW_CAUSE:
        lines += ["## Required response", "",
                  "The hospital must reply within **5 days** of receipt with the documents that answer the "
                  "findings above. The claim remains withheld.", ""]
        if d.documents_requested:
            lines += ["Documents requested:", ""] + [f"- {_inline(x)}" for x in d.documents_requested] + [""]
    if d.committee_brief is not None and d.action in (Action.ESCALATE_SEC, Action.DELIST_SPECIALTY):
        lines += _brief(d)
    elif d.action is Action.ESCALATE_SEC and d.gate == "unknown":
        lines += ["## Question for the Committee", "",
                  "The evidence would warrant suspension, but what this hospital provides - and so what suspending "
                  "it would remove - could not be established from the registry and network data. Should the "
                  "Committee verify the hospital's services first, suspend now, or pursue recovery and penalty "
                  "without suspension?", ""]
    elif d.action is Action.ESCALATE_SEC:
        stake = "; ".join(stake_phrase(x) for x in d.access_at_stake) or "a specialty"
        lines += ["## Question for the Committee", "",
                  f"The evidence would warrant suspension, but in its district this hospital is {stake}. Should the "
                  "Committee suspend and accept the access loss, suspend with a transition window, or pursue recovery "
                  "and penalty without suspension?", ""]
    elif d.action is Action.DELIST_SPECIALTY:
        lines += ["## Question for the Committee", "",
                  "The registry lists this facility as the district's only provider of a specialty its facility "
                  "tier cannot plausibly deliver. De-listing removes access that may not exist and exposes a real "
                  "coverage gap. Confirm the site findings and arrange an alternative provider for the district before "
                  "acting.", ""]
    lines += ["## Explanation", "", draft or d.explanation, ""]
    return "\n".join(lines)


def execute(d: Decision, claim: Claim, hit: TriggerHit | None, package: Package | None,
            out_dir: Path = OUT, draft: str | None = None) -> str | None:
    if d.action in (Action.RELEASE_CLAIM, Action.REFUSE):
        return None
    art = out_dir / "artefacts"
    art.mkdir(parents=True, exist_ok=True)
    path = art / f"{d.action.value}_{d.case_id}.md"
    if path.resolve().parent != art.resolve():
        # The schema already restricts claim ids; this is the last line: nothing is written outside artefacts/ (F-37).
        raise ValueError(f"refusing to write an artefact outside {art}: case id {d.case_id!r}")
    path.write_text(render(d, claim, hit, package, draft), encoding="utf-8")
    if d.action is Action.FIELD_AUDIT:
        with (out_dir / "field_audit_queue.jsonl").open("a", encoding="utf-8") as q:
            q.write(json.dumps({"case_id": d.case_id, "claim_id": d.claim_id, "hospital_ref": d.hospital_ref,
                                "channels": [c.value for c in d.field_channels_ordered]}) + "\n")
    return path.relative_to(out_dir).as_posix()      # relative, so the log is identical wherever it runs (AC-7)


def check_log(out_dir: Path = OUT) -> bool:
    """True when the log must be started (absent or empty); raises when it exists with other columns. Called
    before anything is written, so a refused log never leaves an artefact with no log row behind it."""
    path = out_dir / "decision_log.csv"
    if not path.exists() or path.stat().st_size == 0:
        return True
    with path.open(newline="", encoding="utf-8") as fh:
        header = next(csv.reader(fh), [])
    if header != LOG_FIELDS:
        # Appending under another version's header would shift every column of every new row, silently.
        raise ValueError(f"{path} was written with different columns; start a new output directory")
    return False


def append_log(d: Decision, out_dir: Path = OUT) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "decision_log.csv"
    new = check_log(out_dir)
    a = d.adequacy
    row = {
        "case_id": d.case_id, "claim_id": d.claim_id, "hospital_ref": d.hospital_ref, "trigger_id": d.trigger_id,
        "triggers_fired": "|".join(d.triggers_fired), "severity": d.severity.value if d.severity else "",
        "action": d.action.value, "claim_withheld": d.claim_withheld, "human_required": d.human_required,
        "gate": d.gate or "", "confidence": d.confidence, "degraded": d.degraded,
        "channels_used": "|".join(c.value for c in d.channels_used),
        "field_channels_ordered": "|".join(c.value for c in d.field_channels_ordered),
        "district": f"{a.district}, {a.state}" if a else "", "specialty": a.specialty if a else "",
        "n_providers": a.n_providers if a else "",
        "km_to_alternative": "" if not a or a.km_to_alternative is None else round(a.km_to_alternative, 1),
        "population": a.population if a else "", "aspirational": a.aspirational if a else "",
        "capability_ok": a.capability_ok if a else "",
        "specialties_at_stake": "|".join(x.specialty for x in d.access_at_stake),
        "reason_codes": "|".join(d.reason_codes),
        "conflicts": " ; ".join(d.conflicts), "artefact_path": d.artefact_path or "",
        "decided_ts": d.decided_ts.isoformat(), "model": d.model or "", "acted_by": d.acted_by,
        "tools_called": "|".join(f"{t.agent}:{t.tool}{':refused' if t.refused else ''}" for t in d.trail),
        "agents": "|".join(d.agents), "disputed": "|".join(d.disputed),
    }
    with path.open("a", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=LOG_FIELDS)
        if new:
            w.writeheader()
        w.writerow(row)
