"""The bundled map against the cases it has to be able to draw.

`frontend/src/lib/india-map.json` is generated by `scripts/build_india_map.py` from ~56 MB of
boundary data that is deliberately not committed. So these tests read the committed output rather
than rebuilding it: they run in a bare checkout, with no cache and no network.

Two failures they exist to catch:

  * a district the run refers to that the map has no shape for, which would silently drop a marker
    off the locator and leave the case page quietly less informative than it claims to be;
  * a boundary depiction that stops showing the full extent India claims, which for an Indian
    submission is not a cosmetic problem.
"""
import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "frontend" / "src" / "lib" / "india-map.json"
CASES = ROOT / "frontend" / "static" / "data" / "cases.json"

# "Gonda, 83 km away" -- the same prose `crew/actions.py` writes and the exporter reads back.
NEAREST = re.compile(r"^(?P<district>[^|]+?),\s*[\d.]+\s*km away$")


@pytest.fixture(scope="module")
def india():
    if not MAP.exists():
        pytest.skip(f"{MAP.relative_to(ROOT)} is not built; run python -m scripts.build_india_map")
    return json.loads(MAP.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def cases():
    if not CASES.exists():
        pytest.skip("frontend data is not exported; run python -m scripts.export_frontend")
    return json.loads(CASES.read_text(encoding="utf-8"))


def test_every_state_and_union_territory_is_present(india):
    """36 shapes: 28 states and 8 union territories, at the 2011 vintage the source carries."""
    assert len(india["states"]) == 36
    names = {state["name"] for state in india["states"]}
    for expected in ("Uttar Pradesh", "Madhya Pradesh", "Gujarat", "Maharashtra", "Karnataka"):
        assert expected in names


def test_the_boundary_shows_the_full_extent_india_claims(india):
    """The reason this source was chosen over Natural Earth and the rest.

    Jammu & Kashmir has to reach the top of the canvas and the far side of Aksai Chin. If a future
    rebuild swaps in a source that draws the line of control instead, the state's box shrinks and
    this fails -- which is the point."""
    jk = next(state for state in india["states"] if state["name"] == "Jammu & Kashmir")
    x0, y0, x1, y1 = jk["bbox"]
    # y counts downwards from the north edge, so the northernmost point is a small y.
    assert y0 < 12, "Jammu & Kashmir does not reach the northern extent (Gilgit-Baltistan)"
    assert x1 > 320, "Jammu & Kashmir does not reach the eastern extent (Aksai Chin)"
    assert x0 < 180 and y1 > 150

    # Arunachal Pradesh entire, and the island territories drawn rather than dropped as slivers by
    # the minimum-area filter. The source misspells Arunachal; STATE_NAMES normalises it, and this
    # is where that normalisation is checked.
    drawn = {state["name"] for state in india["states"] if state["d"]}
    assert "Arunachal Pradesh" in drawn
    assert "Andaman & Nicobar Islands" in drawn
    assert "Lakshadweep" in drawn


def test_district_names_are_unique_so_a_bare_name_resolves(india):
    """`findDistrict` in the front end looks a district up by name alone, because the nearest
    alternative is recorded without a state. That is only safe while no two carried districts
    share a name."""
    names = [district["name"] for district in india["districts"]]
    assert len(names) == len(set(names)), f"duplicate district names: {sorted(names)}"


def test_the_map_carries_every_district_a_case_names(india, cases):
    """Both the district a case sits in and the district its nearest alternative sits in."""
    carried = {district["name"] for district in india["districts"]}
    wanted: set[str] = set()
    for case in cases:
        access = case.get("access") or {}
        if access.get("district"):
            wanted.add(access["district"])
        if access.get("nearest_alternative_district"):
            wanted.add(access["nearest_alternative_district"])
        for stake in case.get("at_stake") or []:
            if stake.get("nearest_alternative_district"):
                wanted.add(stake["nearest_alternative_district"])
    missing = wanted - carried
    assert not missing, (
        f"cases name districts the map cannot draw: {sorted(missing)}. "
        "Add them to DISTRICTS in scripts/build_india_map.py and rebuild."
    )


def test_the_alternative_named_in_prose_matches_the_extracted_district(cases):
    """The exporter recovers the district from the artefact's prose. If the two ever disagree the
    map would draw a journey to somewhere the notice does not mention."""
    for case in cases:
        access = case.get("access") or {}
        prose, district = access.get("nearest_alternative"), access.get("nearest_alternative_district")
        match = NEAREST.match(prose.strip()) if prose else None
        assert district == (match.group("district").strip() if match else None), case["claim_id"]


def test_every_shape_is_a_closed_path_inside_the_canvas(india):
    width, height = india["width"], india["height"]
    shapes = [*india["states"], *india["districts"]]
    assert india["outline"].startswith("M") and india["outline"].endswith("Z")
    for shape in shapes:
        assert shape["d"].startswith("M"), shape["name"]
        assert shape["d"].endswith("Z"), shape["name"]
        x0, y0, x1, y1 = shape["bbox"]
        assert 0 <= x0 <= x1 <= width + 1, shape["name"]
        assert 0 <= y0 <= y1 <= height + 1, shape["name"]
        # The anchor a marker hangs from must be inside the shape's own box.
        assert x0 <= shape["cx"] <= x1, shape["name"]
        assert y0 <= shape["cy"] <= y1, shape["name"]


def test_a_district_sits_inside_the_state_it_claims(india):
    states = {state["name"]: state for state in india["states"]}
    for district in india["districts"]:
        state = states.get(district["state"])
        assert state is not None, f"{district['name']} names an unknown state {district['state']}"
        sx0, sy0, sx1, sy1 = state["bbox"]
        dx0, dy0, dx1, dy1 = district["bbox"]
        assert sx0 - 1 <= dx0 and dx1 <= sx1 + 1, district["name"]
        assert sy0 - 1 <= dy0 and dy1 <= sy1 + 1, district["name"]


def test_it_records_where_the_boundaries_came_from(india):
    """Provenance is a standing constraint on this project, and a map is a figure like any other."""
    source = india["_source"]
    assert "datameet" in source["repository"].lower()
    assert re.fullmatch(r"[0-9a-f]{40}", source["commit"]), "the source must be pinned to a commit"
    assert "MIT" in source["licence"]
    assert source["generated_by"] == "scripts/build_india_map.py"
    assert india["projection"]["name"] == "Albers equal-area conic"
