/**
 * The bundled map of India, and the small amount of arithmetic the map components need.
 *
 * `india-map.json` is generated by `scripts/build_india_map.py` from DataMeet's MIT-licensed
 * boundaries; see that script for the provenance and why that source was chosen over the usual
 * Western ones. It is imported as a module rather than fetched, which matters twice over: the
 * geometry ends up inside the prerendered HTML, so the map draws with the network off *and* with
 * JavaScript off — the state the viewer is in when the build is opened straight from disk.
 *
 * Nothing here re-derives a figure. The map colours numbers the evaluation already published.
 */
import raw from './india-map.json';

export interface MapShape {
	name: string;
	/** SVG path data, `fill-rule: evenodd` so island groups and enclaves draw correctly. */
	d: string;
	/** Area-weighted centroid of the largest ring: where a label or marker sits. */
	cx: number;
	cy: number;
	/** `[x0, y0, x1, y1]`, which lets a page crop the viewBox to one region. */
	bbox: [number, number, number, number];
}

export interface MapDistrict extends MapShape {
	state: string;
}

export interface IndiaMap {
	_source: {
		repository: string;
		commit: string;
		licence: string;
		boundaries: string;
		generated_by: string;
	};
	projection: {
		name: string;
		standard_parallels: number[];
		origin: number[];
		tolerance: number;
	};
	width: number;
	height: number;
	outline: string;
	states: MapShape[];
	districts: MapDistrict[];
}

export const india = raw as IndiaMap;

/**
 * The evaluation names states exactly as the map does, and `test_india_map.py` keeps it that way.
 * This is the belt to that braces: a name that somehow fails to match should leave the state
 * unshaded rather than throw, because a missing shade is visibly wrong and a crash is a blank page.
 */
export function stateByName(name: string): MapShape | undefined {
	return india.states.find((state) => state.name === name);
}

export function districtByName(name: string, state: string): MapDistrict | undefined {
	return india.districts.find((entry) => entry.name === name && entry.state === state);
}

/**
 * A district by name alone.
 *
 * The nearest alternative is recorded as a district name with no state — it is a neighbour, and a
 * neighbour is often across a state line (Barwani's is Nandurbar, in Maharashtra). The map carries
 * only the handful of districts the run refers to, so the name is unambiguous within it;
 * `test_india_map.py` fails if two of them ever share a name.
 */
export function findDistrict(name: string): MapDistrict | undefined {
	return india.districts.find((entry) => entry.name === name);
}

/** A district the map calls out, and the tone it is called out in. */
export interface MapPin {
	name: string;
	state: string;
	/**
	 * `gate` tones mirror the gate badge, so a district reads the same on the map as in the table.
	 * `alternative` is the district a patient would travel to instead — evidence, not an outcome.
	 */
	tone: 'protect' | 'phantom' | 'clear' | 'plain' | 'alternative';
	label: string;
	detail?: string;
	href?: string;
}

/** The journey between a district and its nearest alternative provider. */
export interface MapConnector {
	from: { name: string; state: string };
	to: { name: string; state: string };
	label: string;
}

export interface Scale {
	min: number;
	max: number;
	/** Upper edge of every bin but the last. `bins.length` is one less than the number of steps. */
	bins: number[];
	steps: number;
	/** 0-based step for a value, clamped. */
	bin(value: number): number;
	/** Inclusive-lower, exclusive-upper bounds of a step, for the legend. */
	range(step: number): [number, number];
}

/**
 * Equal-interval steps across the observed range.
 *
 * Quantiles would spread the ten states evenly across the ramp and flatter the spread; equal
 * intervals show that Karnataka's load really is several times Jharkhand's. The legend prints the
 * bounds either way, so the reader is never asked to infer a number from a colour.
 */
export function makeScale(values: number[], steps = 5): Scale {
	const usable = values.filter((value) => Number.isFinite(value));
	const min = usable.length ? Math.min(...usable) : 0;
	const max = usable.length ? Math.max(...usable) : 1;
	const span = max - min;
	const width = span === 0 ? 1 : span / steps;
	const bins = Array.from({ length: steps - 1 }, (_, i) => min + width * (i + 1));

	return {
		min,
		max,
		bins,
		steps,
		bin(value: number): number {
			if (!Number.isFinite(value)) return 0;
			if (span === 0) return steps - 1;
			const step = Math.floor((value - min) / width);
			return Math.max(0, Math.min(steps - 1, step));
		},
		range(step: number): [number, number] {
			const low = min + width * step;
			const high = step === steps - 1 ? max : min + width * (step + 1);
			return [low, high];
		}
	};
}

/** Reads a column out of the evaluation's loosely-typed table rows. */
export function numeric(row: Record<string, number | string>, key: string): number {
	const value = row[key];
	return typeof value === 'number' ? value : Number.NaN;
}

export function text(row: Record<string, number | string>, key: string): string {
	const value = row[key];
	return typeof value === 'string' ? value : '';
}

/**
 * Where a tooltip should sit relative to its anchor, so it never leaves the frame. Purely a
 * function of position, which keeps it testable and keeps the component free of measurement.
 */
export function anchorPlacement(
	cx: number,
	cy: number,
	box: Box = { x: 0, y: 0, width: india.width, height: india.height }
): { side: 'left' | 'right'; vertical: 'above' | 'below' } {
	return {
		side: cx > box.x + box.width * 0.62 ? 'left' : 'right',
		vertical: cy < box.y + box.height * 0.28 ? 'below' : 'above'
	};
}

export interface Box {
	x: number;
	y: number;
	width: number;
	height: number;
}

export const WHOLE_COUNTRY: Box = {
	x: 0,
	y: 0,
	width: india.width,
	height: india.height
};

/**
 * A viewBox around some shapes, padded and then grown to a minimum size.
 *
 * A case page shows one district beside its nearest alternative. Cropped tight, two neighbouring
 * districts fill the frame and the reader loses the country entirely; `minimum` keeps enough
 * context around them to recognise where in India this is.
 */
export function crop(shapes: MapShape[], padding = 28, minimum = 150): Box {
	if (shapes.length === 0) return WHOLE_COUNTRY;
	let x0 = Infinity;
	let y0 = Infinity;
	let x1 = -Infinity;
	let y1 = -Infinity;
	for (const shape of shapes) {
		const [sx0, sy0, sx1, sy1] = shape.bbox;
		x0 = Math.min(x0, sx0);
		y0 = Math.min(y0, sy0);
		x1 = Math.max(x1, sx1);
		y1 = Math.max(y1, sy1);
	}
	x0 -= padding;
	y0 -= padding;
	x1 += padding;
	y1 += padding;

	const grow = (low: number, high: number): [number, number] => {
		const short = minimum - (high - low);
		if (short <= 0) return [low, high];
		return [low - short / 2, high + short / 2];
	};
	[x0, x1] = grow(x0, x1);
	[y0, y1] = grow(y0, y1);

	return { x: x0, y: y0, width: x1 - x0, height: y1 - y0 };
}

/** Whether a shape has any chance of appearing inside a crop — a cheap rectangle overlap. */
export function intersects(shape: MapShape, box: Box): boolean {
	const [x0, y0, x1, y1] = shape.bbox;
	return x0 <= box.x + box.width && x1 >= box.x && y0 <= box.y + box.height && y1 >= box.y;
}

export const viewBox = (box: Box): string =>
	`${round(box.x)} ${round(box.y)} ${round(box.width)} ${round(box.height)}`;

const round = (value: number): number => Math.round(value * 10) / 10;
