// Generated by scripts/export_frontend.py. Do not edit by hand.
// Re-run the export after any change to the decision log or the results, and keep this file with it:
// a mismatch between the export and these interfaces is the most likely way the build breaks.

export const CONFIDENCE_FLOOR = 0.7;
export const DISTANCE_MATERIAL_KM = 50.0;

export type ActionKey =
	| 'release_claim'
	| 'order_field_audit'
	| 'no_action_review'
	| 'show_cause_notice'
	| 'suspend_hospital'
	| 'escalate_to_sec'
	| 'delist_specialty'
	| 'refuse_malformed';

export type ActionGroup = 'released' | 'deferred' | 'enforced' | 'refused';

/** Only computed for actions that would remove a provider. `null` is not `clear`. */
export type GateState = 'clear' | 'protect' | 'phantom' | 'unknown';

export type AgentKey =
	| 'case_router'
	| 'desk_investigator'
	| 'billing_analyst'
	| 'provider_advocate'
	| 'medical_auditor'
	| 'field_evidence_analyst'
	| 'audit_reviewer'
	| 'committee_liaison'
	| 'enforcement_officer';

export type Stance = 'supports' | 'opposes' | 'inconclusive';

export interface RosterEntry {
	key: AgentKey;
	title: string;
	owns: string;
	/** Whether this agent worked the case at all. */
	ran: boolean;
	/** Position in the order the agents worked, or null when it did not run. */
	order: number | null;
	/** Ran because a rule mandated it. The Router may only widen the mandatory set. */
	mandatory: boolean;
	opened_by_router: boolean;
	router_reason: string | null;
}

export interface Finding {
	/** The reading, not the agent: desk_audit, medical_audit, field_review, ... */
	reading: string;
	reading_title: string;
	agent_key: AgentKey | null;
	agent_title: string;
	channel: string | null;
	stance: Stance;
	confidence: number;
	conclusion: string;
	citation: string | null;
	/** Set aside by the Audit Reviewer: it now weighs nothing. */
	disputed: boolean;
	/** The reviewer tried to dispute it and was refused: the reading repeats a measurement. */
	dispute_refused: boolean;
}

export interface ToolCall {
	n: number;
	agent_key: AgentKey | null;
	agent_title: string;
	tool: string;
	arguments: { name: string; value: string }[];
	outcome: string;
	refused: boolean;
}

export interface Access {
	district: string | null;
	state: string | null;
	specialty: string | null;
	specialty_name: string | null;
	hospital_listed: boolean | null;
	n_providers: number | null;
	/** `null` means no alternative is listed at all -- a stronger signal than a large number. */
	km_to_alternative: number | null;
	nearest_alternative: string | null;
	/** Just the district, recovered from that prose, so the map can draw the journey. Null when no
	    other district is named -- an alternative inside the same district involves no travel. */
	nearest_alternative_district: string | null;
	population: number | null;
	aspirational: boolean | null;
	capability_ok: boolean | null;
	capability_reason: string | null;
}

export interface AtStake {
	specialty_name: string;
	n_providers: number | null;
	nearest_alternative: string;
	nearest_alternative_district: string | null;
	why_protected: string;
}

export interface Trigger {
	trigger_id: string | null;
	name: string | null;
	severity: number | null;
	evidence: string | null;
	source: string | null;
}

export interface Package {
	code: string;
	name: string;
	published_rate: string;
	claimed_rs: number | null;
}

export interface Defence {
	explanation: string | null;
	/** false means the evidence did not exclude it, which stops an unreviewed action. */
	excluded: boolean | null;
}

export interface CommitteeBrief {
	summary: string | null;
	options: { option: string; consequence: string }[];
	recommendation: string | null;
	question: string | null;
}

export interface RouterOpened {
	track: string | null;
	agent_key: AgentKey | null;
	reason: string;
}

export interface Case {
	case_id: string;
	claim_id: string;
	hospital_ref: string;
	trigger_id: string | null;
	trigger: Trigger | null;
	triggers_fired: string[];
	severity: number | null;
	package: Package | null;
	action: ActionKey;
	action_label: string;
	action_group: ActionGroup;
	claim_withheld: boolean;
	human_required: boolean;
	gate: GateState | null;
	gate_label: string | null;
	confidence: number;
	below_floor: boolean;
	/** The model was unavailable and the deterministic rules decided alone: no crew data at all. */
	degraded: boolean;
	channels_used: string[];
	field_channels_ordered: string[];
	access: Access | null;
	specialties_at_stake: string[];
	at_stake: AtStake[];
	reason_codes: string[];
	conflicts: string[];
	findings: Finding[];
	agents: AgentKey[];
	roster: RosterEntry[];
	router_opened: RouterOpened[];
	defence: Defence | null;
	review: string | null;
	disputed: string[];
	disputes_refused: string[];
	trail: ToolCall[];
	tools_called: string[];
	committee_question: string | null;
	brief: CommitteeBrief | null;
	explanation: string | null;
	channels_ordered: string[];
	field_questions: string[];
	field_checklist: string[];
	documents_requested: string[];
	field_audit_queue: string[];
	artefact_path: string | null;
	artefact_title: string | null;
	/** The issued notice or order as Markdown. Released and refused claims issue none. */
	artefact: string | null;
	mode: string | null;
	decided_ts: string | null;
	model: string | null;
	acted_by: string | null;
}

export interface Meta {
	generated_at: string;
	model: string | null;
	counts: { cases: number; degraded: number; crewed: number };
	source_run: string;
	confidence_floor: number;
	distance_material_km: number;
}

export interface OutcomeSplit {
	innocent: { correct: number; costly: number; wrong: number; n: number };
	fraud: { correct: number; acceptable: number; wrong: number; n: number };
	wrong: number;
	correct: number;
	n: number;
}

export interface BenchmarkCase {
	case_id: string;
	trigger: string;
	truth: 'fraud' | 'innocent';
	reading: string;
	action: ActionKey | null;
	score: 'correct' | 'costly' | 'acceptable' | 'wrong' | null;
	confidence: number | null;
	degraded: boolean;
	acted_by: string | null;
	model: string | null;
	agents: string[];
	disputed: string[];
	disputes_refused: string[];
	opened_by_router: string[];
	desk_stance: string | null;
	desk_confidence: number | null;
	desk_conclusion: string | null;
	medical_stance: string | null;
	medical_confidence: number | null;
	medical_conclusion: string | null;
	billing_stance: string | null;
	billing_confidence: number | null;
	billing_conclusion: string | null;
	defence: string | null;
	defence_excluded: boolean | null;
	review: string | null;
	refused_calls: number | null;
	llm_calls: number | null;
	seconds: number | null;
}

export interface BenchmarkSeries {
	key: string;
	label: string;
	n_cases: number | null;
	scored: number | null;
	overall: OutcomeSplit;
	by_reading: Record<string, OutcomeSplit>;
	by_trigger: Record<string, OutcomeSplit>;
	crew: Record<string, unknown> | null;
	cases: BenchmarkCase[];
}

export interface Benchmark {
	cases: number | null;
	fraud: number | null;
	readings: string[];
	series: Record<string, BenchmarkSeries>;
	caveat: string;
}

export interface Evaluation {
	config: Record<string, unknown>;
	summary: {
		flagged_cases: number;
		fraud_share_of_flags: number;
		auto_resolution_share: number;
		resolved_at_desk_share: number;
		field_audit_share: number;
		human_share: number;
		final_actions: Record<string, number>;
		innocent: Record<string, number>;
		fraud: Record<string, number>;
		confirmed_egregious_share: number;
		per_year: Record<string, number>;
	};
	gate_at_chosen_km: { protect: number; phantom: number; removes_only_provider: number };
	distance_material_km: number;
	confidence_floor: number;
	by_trigger: Record<string, number | string>[];
	by_state: Record<string, number | string>[];
	allocation_fit: Record<string, number | string>[];
	threshold_sweep: Record<string, number | null>[];
	sensitivity: Record<string, number | string | null>[];
	ablation: Record<string, number | string | null>[];
	disparate_impact: Record<string, number | string | null>[];
	caveats: Record<string, string>;
	limitations: string[];
}
